[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://kit.fontawesome.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://use.fontawesome.com https://kit-free.fontawesome.com https://ka-f.fontawesome.com; font-src 'self' https://fonts.gstatic.com https://use.fontawesome.com https://kit-free.fontawesome.com https://ka-f.fontawesome.com; img-src 'self' data:; connect-src 'self' https://ka-f.fontawesome.com;"

[build]
  publish = "."